version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-ms
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grati_store
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  api:
    container_name: api-gratiStore
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: DEFAULT
      MYSQL_URL: jdbc:mysql://mysql:3306/grati_store
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root

  front:
      container_name: front-gratiStore
      build:
        context: ../front-gratiStore
        dockerfile: Dockerfile
      depends_on:
        - api
      ports:
        - "5500:80"

  rabbitmq:
      image: rabbitmq:3.13-management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: root
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
