spring:
  application:
    name: grati-store
  profiles:
    active: "local"
  datasource:
    url: jdbc:mysql://${MYSQL_URL}/grati-store
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
